<?php

/**
 * Copyright (c) 2024 Juan Valero
 *
 * Licensed under the MIT License
 * For full copyright and license information, please refer to the LICENSE file.
 */

declare(strict_types=1);

namespace Milceo\DI\Definition\Function;

use Milceo\DI\Resolver;

/**
 * A callable definition is a definition that returns a value generated by a callable.
 *
 * Callable parameters are resolved by looking up definitions in the container.
 *
 * Some parameters may not have a definition, in which case they will be resolved using auto wiring.
 */
class CallableDefinition extends AbstractFactoryDefinition
{
    /**
     * CallableDefinition constructor.
     *
     * @param callable $callable $callable The callable to invoke.
     */
    public function __construct(callable $callable)
    {
        parent::__construct(new \ReflectionFunction($callable(...)));
    }

    #[\Override]
    protected function invoke(Resolver $resolver, array $parameters): mixed
    {
        return $this->function->invokeArgs($parameters);
    }
}
